### ISSUE TITLE
sad doesn't work when keys are remapped and in visual mode

### ISSUE THREAD

**Issue by mohammed-elhakim-sociomantic** [hauleth/sad.vim#12]
As the title says, when using:
```
nmap <leader>s <Plug>(sad-change-forward)
nmap <leader>S <Plug>(sad-change-backward)
```
A command such as `ve<Leader>s` doesn't do what is expected.

**Comment by hauleth** [comment]
`nmap` is only for normal mode. The fix is to add mappings using `xmap` for Visual mode. I will post a fix in documentation soon.

**Comment by mohammed-elhakim-sociomantic** [comment]
Ah! Thanks for the clarification!
