### ISSUE TITLE
Set `ignore-this-occurrence` keybinding

### ISSUE THREAD

**Issue by cinghiopinghio** [hauleth/sad.vim#14]
Cool small plugin!
I thought it would be cool to provide a mean to ignore a substitution, a functionality provided by multiple-cursors for example.
One can bind something like `ue.` to some keys (or just suggesting it on the readme), those keys are quite far from each other on my keyboard... I don't know which keybinding should be used though.

**Comment by hauleth** [comment]
There is `n` and `N` which will do exactly what you need. It will jump to next occurrence and then you can just `.` it further. Does that solve your problem?

**Comment by cinghiopinghio** [comment]
Ok, I didn't find mention to those `n` and `N` mappings. That's exactly what I was looking for.
Probably because it's a built-in feature? Thanks for the input

**Comment by hauleth** [comment]
Yes, this is builtin and it is used to jump to next/previous match on last search.

**Comment by cinghiopinghio** [comment]
Maybe a comment on the `README` can help distracted people like me.
