### ISSUE TITLE
ss / SS are broken? Or require additional configuration?

### ISSUE THREAD

**Issue by 097115** [hauleth/sad.vim#18]
Hotkeys `ss` / `SS` don't seem to work (Vim 8.1.450, latest sad.vim).

`:verbose map ss` shows only mappings for `s`:

    n  s             <Plug>(sad-change-forward)
            Last set from ~/.vim/plugged/sad.vim/plugin/sad.vim line 27
    x  s             <Plug>(sad-change-forward)
            Last set from ~/.vim/plugged/sad.vim/plugin/sad.vim line 27

Or am I missing something obvious? :)

**Comment by hauleth** [comment]
It seems that I forgot update documentations that I have removed these. To use them you need to add:

```viml
nmap ss <Plug>(sad-change-forward-linewise)
nmap SS <Plug>(sad-change-backward-linewise)
```

**Comment by hauleth** [comment]
Close in favour of #5
