### ISSUE TITLE
Working with nohlsearch?

### ISSUE THREAD

**Issue by for-coursera** [hauleth/sad.vim#19]
Is it possible to make sad.vim highlight words being changed even if nohlsearch is set? Looking through your code I noticed that you were [kinda trying to turn it on](https://github.com/hauleth/sad.vim/blob/master/plugin/sad.vim#L11) but for some reason it [doesn't work for me](https://i.imgur.com/FZ4PAwC.gif).

**Comment by hauleth** [comment]
This will not `set hlsearch`, instead it use internal variable `v:hlsearch` which makes sense only when `hlsearch` is already on. I currently do not have in plan supporting environment with `nohlsearch`. I prefer to respect user choice about searches and do not force my preferences.

**Comment by for-coursera** [comment]
Wow, how pathetic. While at the same time clearly not understanding nohlsearch in full.

Nevermind though, forked and done it myself.

**Comment by hauleth** [comment]
I am sorry that you need to use pathetic plugin created by pathetic human.
