### ISSUE TITLE
Custom Mappings not working?

### ISSUE THREAD

**Issue by jwmann** [hauleth/sad.vim#7]
I'm using the suggested format for custom mappings but it doesn't seem to do anything.

![screen shot 2016-12-10 at 6 45 20 pm](https://cloud.githubusercontent.com/assets/436270/21076970/32b133c4-bf09-11e6-8b6d-74c58b5e59eb.PNG)

I can confirm the mappings using `:map <Leader>c` and they do show up.

![screen shot 2016-12-10 at 6 48 25 pm](https://cloud.githubusercontent.com/assets/436270/21076974/44cd655a-bf09-11e6-81e8-8c8de58bebab.PNG)

These mappings are actually just a test to see how the plugin is working.
#### Ideally I would like to fully replace the `c` command with this, since it is basically a glorified change command with built-in repeatability. I almost never use the repeat command with `c` the normal way.

Vim version 8.0 with patches 1-52

**Comment by hauleth** [comment]
What you mean by "not working"?

I am using NeoVim:

```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161128-42847-16pale9/neovim-0.1.7/build/config -I/tmp/neovim-20161128-42847-16pale9/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161128-42847-16pale9/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161128-42847-16pale9/neovim-0.1.7/build/include
Skompilowany przez hauleth@niuniobook

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui      
For differences from Vim, see :help vim-differences

       vimrc systemu: "$VIM/sysinit.vim"
   odwet dla $VIM-a: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

Installed via HomeBrew and my mappungs for `c`:

```
nmap c <Plug>(sad-change-forward)
xmap c <Plug>(sad-change-forward)
```

Are working perfectly fine.

**Comment by jwmann** [comment]
> Installed via HomeBrew and my mappungs for c:
> 
> `nmap c <Plug>(sad-change-forward)`
> `xmap c <Plug>(sad-change-forward)`
> Are working perfectly fine.

Ahh there's the problem.
The mappings you are using are different than the ones listed in the [README](https://github.com/hauleth/sad.vim/blob/master/README.md#but-what-about-interference-between-this-and-vim-sneak)

Just changed it the ones you are using and they work perfectly.
